### ISSUE TITLE
Any plans for wine-platform-8-staging snap?

### ISSUE THREAD

**Issue by n8marti** [mmtrt/wine-platform-7-staging-core20-snap#1]
Not sure of a better way to communicate with you, but are there plans for a wine-platform-8-staging snap package? A snap package that I'm maintaining currently depends on wine-platform-7-staging-core20-snap, but an update in the underlying windows app looks like it will require wine-staging 8.15+ going forward.

**Comment by mmtrt** [comment]
currently no plans at the moment but might do v9 of wine.

**Comment by mmtrt** [comment]
wine platform 9.x devel, staging snaps have been deployed.
